# github ci triggers doc:
# https://docs.microsoft.com/zh-cn/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - version.props

pool:
  vmImage: 'ubuntu-latest'


steps:
- task: PowerShell@2
  name: "build_to_nuget_pakcages"
  displayName: '打包'
  inputs:
    filePath: './nupkg/pack.ps1'
    pwsh: true
    workingDirectory: './nupkg'

- task: PowerShell@2
  name: "publish_to_nuget"
  displayName: '推送到nuget'
  inputs:
    filePath: './nupkg/push_packages.ps1'
    arguments: $(nuget_key)
    pwsh: true
    workingDirectory: './nupkg'

- task: PowerShell@2
  name: "move_nuget_packages"
  displayName: '移动nuget打包结果'
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item -Force -Recurse ./dist $(Build.ArtifactStagingDirectory)
    workingDirectory: './nupkg'

- task: GitHubRelease@1
  name: "create_git_release_tag"
  displayName: '创建release标签'
  inputs:
    gitHubConnection: 'rivenfx'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'gitTag'
    tagPattern: 'v.*'
    releaseNotesFilePath: './RELEASE_NOTES.md'
    assets: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'


